[workspace]
members = [
    "variegated-embassy-ads124s08",
    "variegated-board-features",
    "variegated-board-open-lcc-r2a",
    "variegated-controller",
    "variegated-controller-lib",
    "variegated-embassy-fdc1004",
    "variegated-machine-definition-lelit-bianca",
    "variegated-serial-bootloader",
    "variegated-gicar-8-5-04"
]
resolver = "2"