workspace = { members = [ "open-lcc-board-features", "open-lcc-board-r2a", "open-lcc-controller", "open-lcc-embassy-fdc1004", "open-lcc-serial-bootloader"] }
[package]
name = "open-lcc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
