[workspace]
members = [
    "open-lcc-embassy-ads124s08",
    "open-lcc-board-features",
    "open-lcc-board-r2a",
    "open-lcc-controller",
    "open-lcc-controller-lib",
    "open-lcc-embassy-fdc1004",
    "open-lcc-machine-definition-lelit-bianca",
    "open-lcc-serial-bootloader"
, "open-lcc-gicar-8-5-04"]
resolver = "2"
